# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

secure_input_notification: false
toggle_key: RIGHT_CTRL
matches:
  - trigger: ";lyt"
    replace: "Love you too! 😘"
  - trigger: ";np"
    replace: "No problem!"
  - trigger: ";un"
    replace: "rtvenge"
  - trigger: ";misc"
    replace: "miscellaneous"
  - trigger: ";sg"
    replace: "Sounds good!"
  - trigger: ";lik"
    replace: "LīkNeew"
  - trigger: ";mattname"
    replace: "Matt Biersdorf"
  - trigger: ";wiz"
    replace: "wysiwyg"
  - trigger: ";;hb"
    replace: "Hoverboard"
  - trigger: ";spin4"
    replace: "23.239.30.82"
  - trigger: ";spin6"
    replace: "2600:3c00::f03c:93ff:feb0:e523"
  - trigger: ";hbback"
    replace: "hoverboard-hosting-backups"
  - trigger: ";env"
    replace: "DB_NAME=database_name\nDB_USER=database_user\nDB_PASSWORD=database_password\nDB_PREFIX=wp_\n\nWP_ENV=development\nWP_HOME=https://SITE_NAME.hbserver.dev\nWP_SITEURL=${WP_HOME}"
  - trigger: ";vv"
    replace: "{{clipboard}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ";a11y"
    replace: "accessibility"
  - trigger: ";lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet, dolor sed commodo finibus, libero ante malesuada ligula, sit amet imperdiet ex nulla ac ex. Suspendisse potenti. Fusce a risus sit amet lacus dictum maximus ultrices eu augue. Donec volutpat convallis nulla, non pellentesque metus euismod et. Aenean faucibus dui sit amet est imperdiet, vitae pulvinar velit pretium. Cras ut nulla malesuada, convallis urna in, facilisis ante. Cras nec venenatis ligula. Quisque mollis ac felis in cursus. Nunc ac convallis est. Donec interdum vehicula velit, cursus pellentesque mauris posuere et. Curabitur pulvinar dui et eleifend viverra. Aliquam viverra accumsan nibh, vel mollis magna suscipit ac. Mauris et elit vestibulum, rhoncus augue et, ultricies enim."
