# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Contact Info
  - trigger: ";em"
    replace: "ryan@tvenge.org"
  - trigger: ";wpem"
    replace: "organizers@wpseattle.org"
  - trigger: ";hbph"
    replace: "612.351.2373"
  - trigger: ";hbaddr"
    replace: "3948 Yosemite Ave. S\nSaint Louis Park, MN 55416"
  - trigger: ";hbhi"
    replace: "hi@hoverboardstudios.com"
  - trigger: ";hbun"
    replace: "hoverboard88"
  - trigger: ";lph"
    replace: "612-418-8308"
  - trigger: ";ph"
    replace: "651-707-5465"
  - trigger: ";addr"
    replace: "3002 SW Hinds St Seattle WA 98126"
  - trigger: ";zip"
    replace: "98126"
  - trigger: ";mattem"
    replace: "matt@hoverboardstudios.com"
  - trigger: ";hbem"
    replace: "ryan@hoverboardstudios.com"
  - trigger: ";lun"
    replace: "eaneeb"
  - trigger: ";lem"
    replace: "eaneeb@gmail.com"

  # URLs
  - trigger: ";del"
    replace: "https://www.godaddy.com/help/invite-a-delegate-to-access-my-godaddy-account-12376"
  - trigger: ";mcal"
    replace: "https://calendly.com/mbiersdo/"
  - trigger: ";cal"
    replace: "https://calendly.com/rtvenge"
  - trigger: ";web"
    replace: "https://hoverboardstudios.com"
  - trigger: ";loc"
    replace: "https://localhost:3000"
  - trigger: ";1ty"
    replace: "https://onetimesecret.com"
  - trigger: ";place"
    replace: "https://place-hold.it/$|$/"

  # Markdown
  - trigger: ";mdl"
    replace: "[$|$]('{{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Shorthand
  - trigger: ";lyt"
    replace: "Love you too! 😘"
  - trigger: ";misc"
    replace: "miscellaneous"
  - trigger: ";sg"
    replace: "Sounds good!"
  - trigger: ";lik"
    replace: "LīkNeew"
  - trigger: ";mattname"
    replace: "Matt Biersdorf"
  - trigger: ";wiz"
    replace: "wysiwyg"
  - trigger: ";vv"
    replace: "{{clipboard}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ";a11y"
    replace: "accessibility"
  - trigger: ";lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet, dolor sed commodo finibus, libero ante malesuada ligula, sit amet imperdiet ex nulla ac ex. Suspendisse potenti. Fusce a risus sit amet lacus dictum maximus ultrices eu augue. Donec volutpat convallis nulla, non pellentesque metus euismod et. Aenean faucibus dui sit amet est imperdiet, vitae pulvinar velit pretium. Cras ut nulla malesuada, convallis urna in, facilisis ante. Cras nec venenatis ligula. Quisque mollis ac felis in cursus. Nunc ac convallis est. Donec interdum vehicula velit, cursus pellentesque mauris posuere et. Curabitur pulvinar dui et eleifend viverra. Aliquam viverra accumsan nibh, vel mollis magna suscipit ac. Mauris et elit vestibulum, rhoncus augue et, ultricies enim."

  # Dates
  - trigger: ";date"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%B %e, %Y"
  - trigger: ";gdate"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y-%m-%d"

  # Scripts
  - trigger: ";log"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: script
        params:
          args:
            - python3
            - "%CONFIG%/scripts/login.py"
  - trigger: ";title"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: script
        params:
          args:
            - python3
            - "%CONFIG%/scripts/title.py"
  - trigger: ";low"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: script
        params:
          args:
            - python3
            - "%CONFIG%/scripts/lower.py"
  - trigger: ";adm"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: script
        params:
          args:
            - python3
            - "%CONFIG%/scripts/admin.py"
  - trigger: ";root"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: script
        params:
          args:
            - python3
            - "%CONFIG%/scripts/root.py"
